# Site settings
title: Sarah Nadi
email: nadi[at]ualberta[dot]ca
description: > # this means to ignore newlines until "baseurl:"
  Sarah Nadi, Assistant Professor, Computing Science Department, University of Alberta
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: sarahnadi
github_username:  snadi

sass:
    sass_dir: _sass

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

gems: ['jekyll-relative-links', jekyll-photo-gallery]


collections:
  research:
    output: true
  staff:
    output: true

github: [metadata]

#Jekyll-Photo-Gallery Settings
exiftag:
 sources:
   - resources/gallery/ #Set to location of photos

#MiniMagick
#https://github.com/zroger/jekyll-minimagick
mini_magick:
    photography:
        source: resources/gallery/
        resize: "1280x720"
